// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnU-QtEmkOFLC1dyfY_fOGtwDkxe74T8M',
    appId: '1:1010882334142:android:30af7ccff582f485427def',
    messagingSenderId: '1010882334142',
    projectId: 'kasir-kuliner',
    storageBucket: 'kasir-kuliner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaAyKbWk-P5jHr4LftcloLHS2y4A-u2xA',
    appId: '1:1010882334142:ios:c02bd69561a0eb7c427def',
    messagingSenderId: '1010882334142',
    projectId: 'kasir-kuliner',
    storageBucket: 'kasir-kuliner.firebasestorage.app',
    androidClientId: '1010882334142-tecakimk1tgoarlfv95t9paq9lm07kfv.apps.googleusercontent.com',
    iosClientId: '1010882334142-h9kr4tucnfvf2p00da9a0n9dbsdsluul.apps.googleusercontent.com',
    iosBundleId: 'com.example.kasirKuliner',
  );
}
